# Generated by Django 5.1.2 on 2024-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
