# Generated by Django 5.1.2 on 2024-11-01 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referralcode_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcode',
            old_name='code_expiration_date',
            new_name='expiration_date',
        ),
        migrations.AddConstraint(
            model_name='referralcode',
            constraint=models.UniqueConstraint(fields=('code', 'user'), name='unique_referral_code_per_user'),
        ),
    ]
