# Generated by Django 5.1.2 on 2024-11-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_rename_code_expiration_date_referralcode_expiration_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcode',
            old_name='expiration_date',
            new_name='code_expiration_date',
        ),
    ]
