# Generated by Django 5.1.2 on 2024-11-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_rename_expiration_date_referralcode_code_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='code_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
